# Generated by Django 2.1 on 2020-04-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('username', '用户名'), ('password', '密码'), ('chineseName', '姓名'), ('email', '邮箱'), ('QQ', 'QQ'), ('identity_number', '身份证'), ('cell_phone', '电话'), ('college', '大学'), ('source', '来源')], max_length=20)),
                ('queryContent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Socialusers',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('password', models.CharField(blank=True, max_length=64, null=True)),
                ('chinesename', models.CharField(blank=True, db_column='chineseName', max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('qq', models.CharField(blank=True, db_column='QQ', max_length=15, null=True)),
                ('weibo', models.CharField(blank=True, max_length=300, null=True)),
                ('identity_number', models.CharField(blank=True, max_length=25, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=60, null=True)),
                ('living_place', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': '社工信息表',
                'verbose_name': '社工信息表',
            },
        ),
    ]
